#ifndef METERINGSDKSETTINGS_H_INCLUDED
#define METERINGSDKSETTINGS_H_INCLUDED

#define M_PRODUCT_NAME "@M_PRODUCT_NAME@"
#define M_COMPANY_NAME "@M_COMPANY_NAME@"

#define M_PRODUCT_LEGAL_COPYRIGHT "@M_PRODUCT_LEGAL_COPYRIGHT@"
#define M_PRODUCT_VERSION_MAJOR    @M_PRODUCT_VERSION_MAJOR@
#define M_PRODUCT_VERSION_MIDDLE   @M_PRODUCT_VERSION_MIDDLE@
#define M_PRODUCT_VERSION_MINOR    @M_PRODUCT_VERSION_MINOR@
#define M_PRODUCT_VERSION_TAG      @M_PRODUCT_VERSION_TAG@

#cmakedefine01 M_DYNAMIC
#cmakedefine01 M_UNICODE

#cmakedefine01 M_USE_GDB
#cmakedefine01 M_USE_MFC
#cmakedefine01 M_USE_CRYPTODEV
#cmakedefine01 M_USE_CRYPTOAPI
#cmakedefine01 M_USE_OPENSSL
#cmakedefine M_GLOBAL_MESSAGE_CATALOG_DOMAIN   "@M_GLOBAL_MESSAGE_CATALOG_DOMAIN@"
#cmakedefine01 M_NO_WCHAR_T
#cmakedefine01 M_NO_ENCODING
#cmakedefine01 M_NO_MESSAGE_CATALOG
#cmakedefine01 M_NO_REFLECTION
#cmakedefine01 M_NO_FULL_REFLECTION
#cmakedefine01 M_NO_MULTITHREADING
#cmakedefine01 M_NO_SOCKETS
#cmakedefine01 M_NO_SOCKETS_UDP
#cmakedefine01 M_NO_SOCKETS_SOCKS
#cmakedefine01 M_NO_FILESYSTEM
#cmakedefine01 M_NO_CONSOLE
#cmakedefine01 M_NO_REGISTRY
#cmakedefine01 M_NO_TIME
#cmakedefine01 M_NO_VARIANT
#cmakedefine01 M_NO_VERBOSE_ERROR_INFORMATION
#cmakedefine01 M_NO_PROGRESS_MONITOR
#cmakedefine01 M_NO_BASE64
#cmakedefine01 M_NO_AUTOMATION
#cmakedefine01 M_NO_SERIAL_PORT
#cmakedefine01 M_NO_DYNAMIC_LIBRARY
#cmakedefine01 M_NO_XML
#cmakedefine01 M_NO_JNI
#cmakedefine01 M_NO_MCOM_RAS_DIAL
#cmakedefine01 M_NO_MCOM_MONITOR
#cmakedefine01 M_NO_MCOM_MONITOR_SHARED_POINTER
#cmakedefine01 M_NO_MCOM_MONITOR_SYSLOG
#cmakedefine01 M_NO_MCOM_CHANNEL_SOCKET
#cmakedefine01 M_NO_MCOM_CHANNEL_SOCKET_UDP
#cmakedefine01 M_NO_MCOM_HANDLE_PEER_DISCONNECT
#cmakedefine01 M_NO_MCOM_CHANNEL_MODEM
#cmakedefine01 M_NO_MCOM_FACTORY
#cmakedefine01 M_NO_MCOM_COMMAND_QUEUE
#cmakedefine01 M_NO_MCOM_PASSWORD_AND_KEY_LIST
#cmakedefine01 M_NO_MCOM_PROTOCOL_THREAD
#cmakedefine01 M_NO_MCOM_KEEP_SESSION_ALIVE
#cmakedefine01 M_NO_MCOM_PROTOCOL_C1218
#cmakedefine01 M_NO_MCOM_PROTOCOL_C1221
#cmakedefine01 M_NO_MCOM_PROTOCOL_C1222
#cmakedefine01 M_NO_MCOM_IDENTIFY_METER
#cmakedefine01 M_NO_LUA_COOPERATIVE_IO

#endif
