SET(CPACK_PACKAGE_NAME ${CMAKE_PROJECT_NAME})
SET(CPACK_PACKAGE_VERSION_MAJOR   ${M_PRODUCT_VERSION_MAJOR})
SET(CPACK_PACKAGE_VERSION_MINOR   ${M_PRODUCT_VERSION_MIDDLE})
SET(CPACK_PACKAGE_VERSION_PATCH   ${M_PRODUCT_VERSION_MINOR})
SET(CPACK_PACKAGE_VERSION_RELEASE ${M_PRODUCT_VERSION_TAG})
SET(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}.${CPACK_PACKAGE_VERSION_RELEASE}-${CMAKE_SYSTEM_PROCESSOR}")
SET(CPACK_PACKAGE_VENDOR ${M_COMPANY_NAME})

IF(UNIX)
  SET(CPACK_BINARY_DEB  ON)
  SET(CPACK_BINARY_STGZ ON)
  SET(CPACK_BINARY_TZ   ON)
  SET(CPACK_BINARY_TBZ2 ON)

  SET(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6 (>= 2.3.6)")
ENDIF()

INCLUDE(CPack)
