SET(CMAKE_SYSTEM_NAME LinuxARMuClibc)

SET(CROSS_COMPILER_PREFIX arm-linux-uclibcgnueabi-)
SET(CROSS_COMPILER_PATH /home/nmacs/buildroot-2010.02/output/staging/usr)

SET(CMAKE_C_COMPILER "${CROSS_COMPILER_PATH}/bin/${CROSS_COMPILER_PREFIX}gcc")
SET(CMAKE_CXX_COMPILER "${CROSS_COMPILER_PATH}/bin/${CROSS_COMPILER_PREFIX}g++")

SET(CMAKE_FIND_ROOT_PATH "${CROSS_COMPILER_PATH}")

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

ADD_DEFINITIONS(-DUCLIBC_RUNTIME)
