SET(CMAKE_SYSTEM_NAME linux_arm_uclinuxeabi)

SET(CMAKE_C_COMPILER "${CC}")
SET(CMAKE_CXX_COMPILER "${CXX}")

# Workaround cmake & uclinux incompatibility
#SET(_CMAKE_TOOLCHAIN_PREFIX "arm-uclinuxeabi-")

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
