// File MCORE/MErrorEnum.cpp

#include "MCOREExtern.h"
#include "MErrorEnum.h"

//
// THIS FILE IS GENERATED, DO NOT EDIT!
// Instead edit library's *Errors.inc files and generate this file with bin/update_errors.py
//

M_START_PROPERTIES(ErrorEnum)
   M_CLASS_ENUMERATION(ErrorEnum, Unknown)
   M_CLASS_ENUMERATION(ErrorEnum, BadConversion)
   M_CLASS_ENUMERATION(ErrorEnum, NoValue)
   M_CLASS_ENUMERATION(ErrorEnum, NumberOutOfRange)
   M_CLASS_ENUMERATION(ErrorEnum, IndexOutOfRange)
   M_CLASS_ENUMERATION(ErrorEnum, StringTooLong)
   M_CLASS_ENUMERATION(ErrorEnum, ClientApplicationError)
   M_CLASS_ENUMERATION(ErrorEnum, InvalidBaud)
   M_CLASS_ENUMERATION(ErrorEnum, UnknownSocketError)
   M_CLASS_ENUMERATION(ErrorEnum, CharactersNotEchoed)
   M_CLASS_ENUMERATION(ErrorEnum, CrcCheckFailed)
   M_CLASS_ENUMERATION(ErrorEnum, C12ServiceResponseOK)
   M_CLASS_ENUMERATION(ErrorEnum, C12ServiceResponseERR)
   M_CLASS_ENUMERATION(ErrorEnum, C12ServiceResponseSNS)
   M_CLASS_ENUMERATION(ErrorEnum, C12ServiceResponseISC)
   M_CLASS_ENUMERATION(ErrorEnum, C12ServiceResponseONP)
   M_CLASS_ENUMERATION(ErrorEnum, C12ServiceResponseIAR)
   M_CLASS_ENUMERATION(ErrorEnum, C12ServiceResponseBSY)
   M_CLASS_ENUMERATION(ErrorEnum, C12ServiceResponseDNR)
   M_CLASS_ENUMERATION(ErrorEnum, C12ServiceResponseDLK)
   M_CLASS_ENUMERATION(ErrorEnum, C12ServiceResponseRNO)
   M_CLASS_ENUMERATION(ErrorEnum, C12ServiceResponseISSS)
   M_CLASS_ENUMERATION(ErrorEnum, C12ServiceResponseSME)
   M_CLASS_ENUMERATION(ErrorEnum, C12ServiceResponseUAT)
   M_CLASS_ENUMERATION(ErrorEnum, C12ServiceResponseNETT)
   M_CLASS_ENUMERATION(ErrorEnum, C12ServiceResponseNETR)
   M_CLASS_ENUMERATION(ErrorEnum, C12ServiceResponseRQTL)
   M_CLASS_ENUMERATION(ErrorEnum, C12ServiceResponseRSTL)
   M_CLASS_ENUMERATION(ErrorEnum, C12ServiceResponseSGNP)
   M_CLASS_ENUMERATION(ErrorEnum, C12ServiceResponseSGERR)
   M_CLASS_ENUMERATION(ErrorEnum, NoSuchProperty)
   M_CLASS_ENUMERATION(ErrorEnum, InvalidChecksum)
   M_CLASS_ENUMERATION(ErrorEnum, ChannelReadTimeout)
   M_CLASS_ENUMERATION(ErrorEnum, CouldNotConnectByModem)
   M_CLASS_ENUMERATION(ErrorEnum, ModemError)
   M_CLASS_ENUMERATION(ErrorEnum, C12ProcedureResultOK)
   M_CLASS_ENUMERATION(ErrorEnum, C12ProcedureNotCompleted)
   M_CLASS_ENUMERATION(ErrorEnum, C12ProcedureInvalidParameter)
   M_CLASS_ENUMERATION(ErrorEnum, C12ProcedureDeviceConflict)
   M_CLASS_ENUMERATION(ErrorEnum, C12ProcedureTimingConstraint)
   M_CLASS_ENUMERATION(ErrorEnum, C12ProcedureNoAuthorization)
   M_CLASS_ENUMERATION(ErrorEnum, C12ProcedureUnknown)
   M_CLASS_ENUMERATION(ErrorEnum, UnknownItem)
   M_CLASS_ENUMERATION(ErrorEnum, CannotConvertToTableOrFunctionNumber)
   M_CLASS_ENUMERATION(ErrorEnum, ChannelWriteTimeout)
   M_CLASS_ENUMERATION(ErrorEnum, UnknownSystemError)
   M_CLASS_ENUMERATION(ErrorEnum, OperationCancelled)
   M_CLASS_ENUMERATION(ErrorEnum, NoSuchService)
   M_CLASS_ENUMERATION(ErrorEnum, UnknownStringEscape)
   M_CLASS_ENUMERATION(ErrorEnum, CannotIndexItem)
   M_CLASS_ENUMERATION(ErrorEnum, BadBcd)
   M_CLASS_ENUMERATION(ErrorEnum, OverflowOrUnderflow)
   M_CLASS_ENUMERATION(ErrorEnum, SocketReadTimeout)
   M_CLASS_ENUMERATION(ErrorEnum, BadFileFormat)
   M_CLASS_ENUMERATION(ErrorEnum, CannotModifyConstantOrReadonly)
   M_CLASS_ENUMERATION(ErrorEnum, EndOfStream)
   M_CLASS_ENUMERATION(ErrorEnum, ClassNotFound)
   M_CLASS_ENUMERATION(ErrorEnum, UnsupportedType)
   M_CLASS_ENUMERATION(ErrorEnum, CannotWriteToReadonlyStream)
   M_CLASS_ENUMERATION(ErrorEnum, CannotReadFromWriteonlyStream)
   M_CLASS_ENUMERATION(ErrorEnum, SocketClosedByPeer)
   M_CLASS_ENUMERATION(ErrorEnum, DataNotValidated)
   M_CLASS_ENUMERATION(ErrorEnum, BadStreamFormat)
   M_CLASS_ENUMERATION(ErrorEnum, ProxySocketError)
   M_CLASS_ENUMERATION(ErrorEnum, SocketWriteTimeout)
   M_CLASS_ENUMERATION(ErrorEnum, BadIpAddress)
   M_CLASS_ENUMERATION(ErrorEnum, ReceivedDataSizeDifferent)
   M_CLASS_ENUMERATION(ErrorEnum, ChannelDisconnectedUnexpectedly)
   M_CLASS_ENUMERATION(ErrorEnum, ReceivedPacketToggleBitFailure)
   M_CLASS_ENUMERATION(ErrorEnum, DeviceReportedBadPacketCRC)
   M_CLASS_ENUMERATION(ErrorEnum, PossibleTamperingDetected)
   M_CLASS_ENUMERATION(ErrorEnum, CollisionDetected)
   M_CLASS_ENUMERATION(ErrorEnum, ChannelConnectTimeout)
M_START_METHODS(ErrorEnum)
M_END_CLASS(ErrorEnum, Object)
