// File MCORE/MErrorEnum.cpp

#include "MCOREExtern.h"
#include "MErrorEnum.h"

//
// THIS FILE IS GENERATED, DO NOT EDIT!
// Instead edit library's *Errors.inc files and generate this file with bin/update_errors.py
//

M_START_PROPERTIES(ErrorEnum)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, Unknown)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, BadConversion)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, NoValue)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, NumberOutOfRange)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, IndexOutOfRange)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, StringTooLong)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, ClientApplicationError)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, InvalidBaud)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, UnknownSocketError)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, CharactersNotEchoed)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, CrcCheckFailed)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ServiceResponseOK)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ServiceResponseERR)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ServiceResponseSNS)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ServiceResponseISC)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ServiceResponseONP)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ServiceResponseIAR)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ServiceResponseBSY)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ServiceResponseDNR)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ServiceResponseDLK)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ServiceResponseRNO)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ServiceResponseISSS)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ServiceResponseSME)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ServiceResponseUAT)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ServiceResponseNETT)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ServiceResponseNETR)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ServiceResponseRQTL)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ServiceResponseRSTL)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ServiceResponseSGNP)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ServiceResponseSGERR)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ServiceResponseNRY)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, NoSuchProperty)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, InvalidChecksum)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, ChannelReadTimeout)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, CouldNotConnectByModem)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, ModemError)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ProcedureResultOK)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ProcedureNotCompleted)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ProcedureInvalidParameter)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ProcedureDeviceConflict)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ProcedureTimingConstraint)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ProcedureNoAuthorization)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, C12ProcedureUnknown)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, UnknownItem)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, CannotConvertToTableOrFunctionNumber)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, ChannelWriteTimeout)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, UnknownSystemError)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, OperationCancelled)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, NoSuchService)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, UnknownStringEscape)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, CannotIndexItem)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, BadBcd)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, OverflowOrUnderflow)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, SocketReadTimeout)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, BadFileFormat)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, CannotModifyConstantOrReadonly)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, EndOfStream)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, ClassNotFound)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, UnsupportedType)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, CannotWriteToReadonlyStream)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, CannotReadFromWriteonlyStream)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, SocketClosedByPeer)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, DataNotValidated)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, BadStreamFormat)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, ProxySocketError)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, SocketWriteTimeout)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, BadIpAddress)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, ReceivedDataSizeDifferent)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, ChannelDisconnectedUnexpectedly)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, ReceivedPacketToggleBitFailure)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, DeviceReportedBadPacketCRC)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, PossibleTamperingDetected)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, CollisionDetected)
   M_CLASS_ENUMERATION_UINT(ErrorEnum, ChannelConnectTimeout)
M_START_METHODS(ErrorEnum)
M_END_CLASS(ErrorEnum, Object)
